app:
  env: dev
  name: go-mall
  log:
    path: "/tmp/applog/go-mall.log"
    max_size: 1 # 单个日志文件最大100M
    max_age: 60 # 备份文件最多保存60天
  pagination:
    default_size: 20
    max_size: 100
  wechat_pay:
    appid: ""
    mchid: ""
    private_serial_no: "" # 证书序列号
    aes_key: ""
    notify_url: "" # 支付结果回调通知地址
database: # 记得更改成自己的连接配置
    type: mysql
    master: 
      dsn: root:ServBay.dev@tcp(localhost:3306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
      maxopen: 100
      maxidle: 10
      maxlifetime: 300000000000 # 300s 内可复用
    slave: 
      dsn: root:ServBay.dev@tcp(localhost:3306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
      maxopen: 100
      maxidle: 10
      maxlifetime: 300000000000 # 300s 内可复用
redis: # 记得更改成自己的连接配置
  addr: 127.0.0.1:6379
  password: 123456
  pool_size: 10
  db: 0
